org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

modId=slimcolonies
modGroup=no.monopixel
modVersion=1.21.1-1.0.0

javaVersion=21
useJavaToolChains=true
fml_range=[4,)

forgeVersion=21.1.80
forgeMinVersion=21.1.0

exactMinecraftVersion=1.21.1
minecraftVersion=1.21.1
additionalMinecraftVersions=server;client;1.21
minecraft_range=[1.21, 1.22)

dataGeneratorsVersion=1.20.4-0.1.57-ALPHA
blockUI_version=1.0.199-1.21.1-snapshot
structurize_version=1.0.832-1.21.1-snapshot
domumOrnamentumVersion=1.0.223-snapshot
multiPistonVersion=1.2.51-1.21.1-snapshot

jei_mcversion=1.21.1
jei_version=19.19.6.235
jmapApiVersion=2.0.0-1.21.1-SNAPSHOT
jmapVersion=1.21.1-6.0.0-beta.29
tinkersConstructVersion=0
mantleVersion=0

runWithJourneymap=false

dynamicTreesMcVersion=1.21.1
dynamicTreesVersion=1.5.0-BETA07
runWithDynamicTrees=false

githubUrl=https://github.com/Barbecude/SlimColonies
gitUrl=https://github.com/Barbecude/SlimColonies.git
gitConnectUrl=https://github.com/Barbecude/SlimColonies.git
projectUrl=https://github.com/Barbecude/SlimColonies

curseId=245506
usesCurse=false
requiredCurseDependencies=structurize;domum-ornamentum;blockui;multi-piston;towntalk

usesCrowdin=false
usesCrowdInVersionSeparation=false
crowdinId=slimcolonies

usesDatagen=true
useDefaultTestSystem=false
runtimeSourceSets=main
librarySourceSets=main;datagen;
projectHasApi=false

extendDefaultSourceSetConfiguration=true
mainExcludedResources=assets/slimcolonies/lang/manual_en_us.json;assets/slimcolonies/lang/default.json;assets/slimcolonies/lang/quests.json

usesMergableTranslations=false
usesSonarQube=false
usesCrowdInTranslationManagement=false

additionalModsInDataGen=structurize;domum_ornamentum